openapi: 3.0.3
info:
  title: Seasons API
  version: 2.0.0
  description: API for managing fields and seasons

paths:

  /api/v2/fields/season:
    post:
      tags:
        - Season
      operationId: saveSeason
      summary: Create a new season
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SeasonDTO'
      responses:
        '200':
          description: Season ID created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdDTO'

    delete:
      tags:
        - Season
      operationId: deleteSeason
      summary: Delete season by seasonId
      parameters:
        - name: seasonId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Season deleted

  /api/v2/fields/seasons:
    get:
      tags:
        - Season
      operationId: findSeasons
      summary: Get all seasons for the organization without fields
      responses:
        '200':
          description: List of seasons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SeasonDTO'

  /api/v2/fields/seasons/full:
    get:
      tags:
        - Season
      operationId: findFullSeasons
      summary: Get all seasons for the organization
      responses:
        '200':
          description: List of seasons
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SeasonWithFieldsDTO'

  /api/v2/fields/contours:
    get:
      tags:
        - Contours
      operationId: findContours
      summary: Get contours by fieldId
      parameters:
        - name: fieldId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Contours
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContourDTO'

  /api/v2/fields/contour:
    delete:
      tags:
        - Contours
      operationId: deleteContour
      summary: Delete contour by contourId
      parameters:
        - name: contourId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Contour deleted

    put:
      tags:
        - Contours
      operationId: changeContour
      summary: Change contour
      parameters:
        - name: contourId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContourDTO'
      responses:
        '200':
          description: Changed

  /api/v2/fields/fields/{fieldId}/contour:
    post:
      tags:
        - Contours
      operationId: saveContour
      summary: add a new contour to exist field
      parameters:
        - name: fieldId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContourDTO'
      responses:
        '200':
          description: Added to Field
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdDTO'

  /api/v2/fields/seasons/{seasonId}/field:
    post:
      tags:
        - Fields
      operationId: saveField
      summary: Create a new field to existing season
      parameters:
        - name: seasonId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FieldDTO'
      responses:
        '200':
          description: Field ID created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdDTO'

  /api/v2/fields/fields:
    get:
      tags:
        - Fields
      operationId: findFields
      summary: Get all fields by season ID
      parameters:
        - name: seasonId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of fields by season
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FieldWithContoursDTO'

  /api/v2/fields/field:
    delete:
      tags:
        - Fields
      operationId: deleteField
      summary: Delete field by fieldId
      parameters:
        - name: fieldId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Field deleted

  /api/v2/fields/contours/{contourId}/crop-rotation:
    post:
      tags:
        - CropRotations
      operationId: saveCropRotation
      summary: Create a new crop rotation
      parameters:
        - name: contourId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CropRotationDTO'
      responses:
        '200':
          description: Crop rotation ID created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdDTO'

  /api/v2/fields/crop-rotations:
    get:
      tags:
        - CropRotations
      operationId: getCropRotations
      summary: Get crop rotations by contourID
      parameters:
        - name: contourID
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Crop rotation details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CropRotationDTO'

  /api/v2/fields/crop-rotation:
    delete:
      tags:
        - CropRotations
      operationId: deleteCropRotation
      summary: Delete crop rotations by cropRotationId
      parameters:
        - name: cropRotationId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Crop rotation deleted

    put:
      tags:
        - CropRotations
      operationId: changeCropRotation
      summary: Change crop rotation
      parameters:
        - name: CropRotationId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCropRotationDTO'
      responses:
        '200':
          description: Changed

  /api/v2/fields/contours/{contourId}/soil-composition:
    post:
      tags:
        - SoilCompositions
      operationId: saveSoilComposition
      summary: Create a new soil composition to existing contour
      parameters:
        - name: contourId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SoilCompositionDTO'
      responses:
        '200':
          description: Soil composition ID created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdDTO'

  /api/v2/fields/contours/{contourId}/soil-compositions:
    get:
      tags:
        - SoilCompositions
      operationId: getSoilCompositions
      summary: Get soil compositions by contourID
      parameters:
        - name: contourId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Crop rotation details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SoilCompositionDTO'

  /api/v2/fields/soil-composition:
    put:
      tags:
        - SoilCompositions
      operationId: changeSoilComposition
      summary: Change SoilComposition
      parameters:
        - name: SoilCompositionId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SoilCompositionDTO'
      responses:
        '200':
          description: Changed

    delete:
      tags:
        - SoilCompositions
      operationId: deleteSoilComposition
      summary: Delete SoilComposition by SoilCompositionId
      parameters:
        - name: soilCompositionId
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: SoilComposition deleted


components:
  schemas:
    FieldDTO:
      type: object
      properties:
        fieldId:
          type: string
          description: The field ID
          readOnly: true
        name:
          type: string
          description: The name of the field
        description:
          type: string
          description: Description of the field
        contours:
          type: array
          items:
            $ref: '#/components/schemas/ContourDTO'
      required:
        - name
        - seasonId

    ContourDTO:
      type: object
      properties:
        contourId:
          type: string
          description: The contour ID
          readOnly: true
        color:
          type: string
          pattern: "^([A-Fa-f0-9]{6})$"
          description: The color must be written in HEX format
        squareArea:
          type: string
          description: The area of the contour
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/CoordinatesDTO'
        cropRotations:
          type: array
          items:
            $ref: '#/components/schemas/CropRotationDTO'
          readOnly: true
        soilCompositions:
          type: array
          items:
            $ref: '#/components/schemas/SoilCompositionDTO'
          readOnly: true
      required:
        - color
        - coordinates

    CoordinatesDTO:
      type: object
      properties:
        longitude:
          type: number
          format: double
          minimum: -180
          maximum: 180
          description: Must be filled
        latitude:
          type: number
          format: double
          minimum: -90
          maximum: 90
          description: Must be filled
      required:
        - longitude
        - latitude

    CropRotationDTO:
      type: object
      properties:
        cropRotationId:
          type: string
          description: The crop rotation ID
          readOnly: true
        contourID:
          type: string
          pattern: "^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$"
          description: Expected UUID
        startDate:
          type: string
          format: date
          description: Start date of the crop rotation
        endDate:
          type: string
          format: date
          description: End date of the crop rotation
        culture:
          type: string
          description: The culture being rotated
        cultivar:
          type: string
          description: The specific cultivar
        description:
          type: string
          description: Description of the crop rotation
      required:
        - contourID
        - startDate
        - endDate
        - culture

    FieldWithContoursDTO:
      type: object
      properties:
        fieldId:
          type: string
          description: The field ID
          readOnly: true
        seasonId:
          type: string
          pattern: "^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$"
          description: Expected UUID
        name:
          type: string
          description: The name of the field
        description:
          type: string
          description: Description of the field
        contours:
          type: array
          items:
            $ref: '#/components/schemas/ContourSummaryDTO'
          description: A list of contours associated with the field
      required:
        - name
        - seasonId

    ContourSummaryDTO:
      type: object
      properties:
        contourId:
          type: string
          description: The contour ID
          readOnly: true
        color:
          type: string
          pattern: "^([A-Fa-f0-9]{6})$"
          description: The color must be written in HEX format
        squareArea:
          type: string
          description: The area of the contour
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/CoordinatesDTO'
          description: Coordinates of the contour
      required:
        - color
        - coordinates

    IdDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Identification
      required:
        - id

    SeasonDTO:
      type: object
      properties:
        seasonId:
          type: string
          readOnly: true
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
      required:
        - startDate
        - endDate

    SoilCompositionDTO:
      type: object
      properties:
        soilCompositionId:
          type: string
          description: The soil composition ID
          readOnly: true
        ph:
          type: string
          description: The pH level of the soil
        contourId:
          type: string
          pattern: "^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$"
          description: Expected UUID
        sampleDate:
          type: string
          format: date
          description: The date when the soil sample was taken
        organicMatter:
          type: string
          description: The organic matter content
        mobileP:
          type: string
          description: The mobile phosphorus content
        mobileK:
          type: string
          description: The mobile potassium content
        mobileS:
          type: string
          description: The mobile sulfur content
        nitrateN:
          type: string
          description: The nitrate nitrogen content
        ammoniumN:
          type: string
          description: The ammonium nitrogen content
        hydrolyticAcidity:
          type: string
          description: Hydrolytic acidity
        caExchange:
          type: string
          description: Calcium exchange content
        mgExchange:
          type: string
          description: Magnesium exchange content
        b:
          type: string
          description: Boron content
        co:
          type: string
          description: Cobalt content
        mn:
          type: string
          description: Manganese content
        zn:
          type: string
          description: Zinc content
      required:
        - contourId
        - sampleDate

    SeasonWithFieldsDTO:
      type: object
      properties:
        seasonId:
          type: string
          description: The season ID
          readOnly: true
        name:
          type: string
          description: The name of the season
        startDate:
          type: string
          format: date
          description: Start date of the season
        endDate:
          type: string
          format: date
          description: End date of the season
        fields:
          type: array
          items:
            $ref: '#/components/schemas/FieldWithContoursAndCropRotationsDTO'
      required:
        - seasonId
        - startDate
        - endDate
        - fields

    FieldWithContoursAndCropRotationsDTO:
      type: object
      properties:
        fieldId:
          type: string
          description: The field ID
          readOnly: true
        name:
          type: string
          description: The name of the field
        description:
          type: string
          description: Description of the field
        contours:
          type: array
          items:
            $ref: '#/components/schemas/ContourWithCropRotationsDTO'
          description: A list of contours with crop rotations
      required:
        - fieldId
        - name
        - contours

    ContourWithCropRotationsDTO:
      type: object
      properties:
        contourId:
          type: string
          description: The contour ID
          readOnly: true
        color:
          type: string
          pattern: "^([A-Fa-f0-9]{6})$"
          description: The color must be written in HEX format
        squareArea:
          type: string
          description: The area of the contour
        coordinates:
          type: array
          items:
            $ref: '#/components/schemas/CoordinatesDTO'
          description: Coordinates of the contour
        cropRotations:
          type: array
          items:
            $ref: '#/components/schemas/CropRotationDTO'
          description: Crop rotations associated with the contour
      required:
        - contourId
        - color
        - coordinates
        - cropRotations

    UpdateContourDTO:
      type: object
      properties:
        color:
          type: string
          pattern: "^([A-Fa-f0-9]{6})$"
          description: The color must be written in HEX format
      required:
        - color

    UpdateCropRotationDTO:
      type: object
      properties:
        endDate:
          type: string
          format: date
          description: End date of the crop rotation
        description:
          type: string
          description: Description of the crop rotation
      required:
        - endDate
